version: '1.0.{build}'
branches:
  only:
    - master
image: Visual Studio 2017
before_build:
- cd src/FizzBuzz
build_script:
- dotnet build
test_script:
  - cd ../../test/FizzBuzzTests
  - dotnet test